suppressMessages({library(mada)})
d <- read.csv("C:/Users/fsy/Desktop/MetaWingman/validation-output/ag-rdt-corpus/case-input/agrdt-2x2-study.csv")
dat <- cbind(d$TP, d$FP, d$TN, d$FN)
colnames(dat) <- c("TP", "FP", "TN", "FN")
fit <- mada::reitsma(dat, correction = 0.5)
s <- summary(fit)
cat("SUMMARY\n")
print(s)
cat("COEF\n")
print(coef(fit))
co <- coef(fit)
se_pooled <- plogis(co[["Intercept (Se)"]])
sp_pooled <- plogis(co[["Intercept (Sp)"]])
cat("POOLED:", round(se_pooled * 100, 2), round(sp_pooled * 100, 2), "\n")
